name:                jps
version:             0.1.0.0
github:              "isovector/jps"
license:             BSD3
author:              "Zachary Kamerling"
maintainer:          "Sandy Maguire <sandy@sandymaguire.me>"
copyright:           "2018 Zachary Kamerling"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Jump point search for Haskell
category:            Algorithm

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/jps#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- vector
- fingertree
- lens

library:
  source-dirs: src
  other-modules: Algorithm.Search.JumpPoint.Pathing

